name: Sync Fork 2.0

on:
  schedule:
    - cron: '0 0 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync-and-tweak:

    runs-on: ubuntu-latest

    steps:
      - name: Sync Branch with Upstream
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          gh repo sync mihaichitic/demo-eaas --branch test-fork-sync --force
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Fetch shallow history for efficiency
          ref: test-fork-sync

      - name: Set config user
        run: |
          git config --global user.email "mchitic@gmail.com"
          git config --global user.name "Mihai"

      - name: Checkout or Create test-fork-sync-bns Branch
        run: |
          git branch
          cat .bunnyshell/templates/preview/bunnyshell.yaml
          #if git show-ref --verify --quiet refs/heads/test-fork-sync-bns; then
          #  echo "test-fork-sync-bns exista"
            git checkout --force -B test-fork-sync-bns refs/remotes/origin/test-fork-sync-bns
            cat .bunnyshell/templates/preview/bunnyshell.yaml
            git rebase test-fork-sync -X theirs || (git rebase --abort && exit 1)
            cat .bunnyshell/templates/preview/bunnyshell.yaml
          #else
          #  echo "test-fork-sync-bns nu exista"
          #  git checkout -b test-fork-sync-bns test-fork-sync
          #fi

      - name: Add .env File
        env:
            BNS_GIT_REPO: 'https://github.com/bunnyshell/OSS-Sylius.git'
            BNS_GIT_BRANCH: '2.0-bns'
            BNS_YAML_PATH: '.bunnyshell/templates/preview/bunnyshell.yaml'
        run: |
          cat $BNS_YAML_PATH
          yq "(.components[] | select(.gitRepo != null)).gitRepo |= \"$BNS_GIT_REPO\"" $BNS_YAML_PATH > $BNS_YAML_PATH
          cat $BNS_YAML_PATH
          yq "(.components[] | select(.gitBranch != null)).gitBranch |= \"$BNS_GIT_BRANCH\"" $BNS_YAML_PATH > $BNS_YAML_PATH
          cat $BNS_YAML_PATH
          git add $BNS_YAML_PATH
          git commit -m "Update bunnyshell.yaml" || echo "No changes to commit"

      - name: Push Updates to test-fork-sync-bns
        run: git push origin test-fork-sync-bns --force
